# Generated by Django 5.2 on 2026-03-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_venta_itemventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
