# Generated by Django 5.2 on 2026-03-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_itemventa_costo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='app.negocio')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
