# Generated by Django 5.2 on 2026-03-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_venta_observacion_nota'),
        ('app', '0007_pedido_itempedido'),
    ]

    operations = [
    ]
