# Generated by Django 5.2 on 2026-03-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('medias', 'Medias'), ('accesorios', 'Accesorios'), ('bazar', 'Bazar'), ('maquillaje', 'Maquillaje'), ('aromas', 'Aromas'), ('papeleria', 'Papelería'), ('unas', 'Uñas'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
