# Generated by Django 5.2 on 2026-03-31 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='nombre_libre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_venta', to='app.producto'),
        ),
    ]
