# Generated by Django 5.2 on 2026-03-31 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_itemventa_nombre_libre_alter_itemventa_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_producto', to='app.negocio')),
            ],
            options={
                'verbose_name_plural': 'Categorias de Producto',
                'ordering': ['nombre'],
            },
        ),
    ]
