# Generated by Django 5.2 on 2026-04-22 20:34

from django.db import migrations

def migrate_tipo_to_categoria(apps, schema_editor):
    Producto = apps.get_model('app', 'Producto')
    CategoriaProducto = apps.get_model('app', 'CategoriaProducto')
    
    for producto in Producto.objects.all():
        tipo_str = producto.tipo or 'Otros'
        # Buscar o crear la categoría correspondiente al texto
        categoria, created = CategoriaProducto.objects.get_or_create(
            negocio=producto.negocio,
            nombre__iexact=tipo_str,
            defaults={'nombre': tipo_str.capitalize()}
        )
        producto.categoria = categoria
        producto.save()

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_itempedido_nombre_producto_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_tipo_to_categoria, reverse_migrate),
    ]
