# Generated by Django 5.2 on 2026-04-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_migrate_tipo_to_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
    ]
