# Generated by Django 5.2 on 2026-04-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_negocio_propietario_alter_negocio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='activa',
            field=models.BooleanField(default=False, help_text='Activá la tienda una vez que el cliente realizó el pago.', verbose_name='Tienda activa'),
        ),
    ]
