# Generated by Django 5.2 on 2026-05-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_negocio_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_movimiento',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra_stock', 'Compra de stock')], default='venta', max_length=15, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia bancaria'), ('mercadopago', 'Mercado Pago'), ('qr', 'QR'), ('egreso', 'Egreso directo'), ('otro', 'Otro')], default='efectivo', max_length=20),
        ),
    ]
