# Generated by Django 6.0.5 on 2026-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_negocio_estilo_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo que se mostrará en la tienda online (fondo blanco o transparente recomendado).', null=True, upload_to='logos/', verbose_name='Logo de la tienda'),
        ),
    ]
