# Generated by Django 6.0.5 on 2026-07-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_subcategoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='tamano_logo',
            field=models.CharField(choices=[('pequeno', 'Pequeño (96px)'), ('mediano', 'Mediano (128px)'), ('grande', 'Grande (192px)')], default='mediano', max_length=10, verbose_name='Tamaño del logo'),
        ),
    ]
