# Generated by Django 6.0.5 on 2026-07-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_negocio_tamano_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='tamano_logo',
            field=models.CharField(choices=[('pequeno', 'Pequeño (96px)'), ('mediano', 'Mediano (128px)'), ('grande', 'Grande (192px)'), ('gigante', 'Gigante (256px)')], default='mediano', max_length=15, verbose_name='Tamaño del logo'),
        ),
    ]
