# Generated by Django 6.0.5 on 2026-08-15 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_negocio_tamano_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('visita', 'Visita a la tienda'), ('busqueda', 'Búsqueda'), ('click_producto', 'Click en producto')], max_length=20)),
                ('detalle', models.CharField(blank=True, help_text='Término de búsqueda u otro detalle', max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_analytics', to='app.negocio')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_analytics', to='app.producto', verbose_name='Producto (para clics)')),
            ],
            options={
                'verbose_name': 'Evento Analytics',
                'verbose_name_plural': 'Eventos Analytics',
                'ordering': ['-fecha'],
            },
        ),
    ]
