# Generated by Django 5.2 on 2026-08-26 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_eventoanalytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('mensaje', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('info', 'Informacion'), ('success', 'Novedad'), ('warning', 'Advertencia'), ('error', 'Urgente')], default='info', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('descartada_por', models.ManyToManyField(blank=True, related_name='notificaciones_descartadas', to=settings.AUTH_USER_MODEL)),
                ('destinatarios', models.ManyToManyField(blank=True, help_text='Dejar vacio para enviar a TODOS. Seleccionar tiendas para envio selectivo.', related_name='notificaciones', to='app.negocio', verbose_name='Destinatarios')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado'],
            },
        ),
    ]
