# Generated by Django 5.2 on 2026-09-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_notificacion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventoanalytics',
            index=models.Index(fields=['negocio', 'tipo', 'fecha'], name='evento_neg_tipo_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['negocio', 'estado'], name='pedido_neg_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['negocio', 'creado'], name='pedido_neg_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['negocio', 'stock'], name='producto_neg_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['negocio', 'categoria'], name='producto_neg_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['negocio', 'subcategoria'], name='producto_neg_subcat_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['negocio', 'fecha'], name='venta_neg_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['negocio', 'creado'], name='venta_neg_creado_idx'),
        ),
    ]
