# Generated by Django 5.2 on 2026-09-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.JSONField(blank=True, default=list, verbose_name='Colores disponibles (hex)'),
        ),
    ]
