# Generated by Django 5.2 on 2026-09-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_producto_colores'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Color (hex)'),
        ),
        migrations.AddField(
            model_name='itemventa',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Color (hex)'),
        ),
    ]
